#language: python
#python:
 # - "3.5"
# command to install dependencies
#install:
 #   - pip install -U pytest
  #  - pip install -r requirements.txt
# command to run tests
#script: 
    #- pytest Test.py
language: python
python:
  - "3.5"

env:
 - PYRAMID_TEST_DB_STRING=sqlite://

install:
 - pip install -U pytest
 - pip install -r requirements.txt
 - pip install -e 
 - pip install -e ".[testing]"

script:
 - py.test --cov --cov-report=term-missing
 #- initialize_faculty_db development.ini
cache:
  directories:
    -passlib

services:
  -mysql
